package config

const (
	AlipayURL             = ""
	AlipayAppID           = ""
	AlipayPrivateKey      = ""
	AlipayPublicKey       = ""
	AlipayNotifyURL       = ""
	AlipayNotifyFreezeURL = ""
	AlipaySellerID        = ""
	WxpayMchURL           = ""
	WxpayMchKey           = ""
	WxpayMchID            = ""
	WxpaySerialNo         = ""
	WxpayAppID            = ""
	WXpayAppSecretV3      = ""
	WxpayPrivateKey       = ""
	WxpayPublicKey        = ""
	WxpayServiceID        = ""
	WxpayScoreNotifyURL   = ""
	WxpayNotifyURL        = ""
	WechatPayCert         = ""
	WechatPayKey          = ""
	WechatRootCa          = ""
)
